openapi: 3.0.0
info:
  title: Patient Management API
  version: 1.0.0
  description: API para gestión de citas de pacientes
servers:
  - url: http://localhost:8282
tags:
  - name: Pacientes
    description: Operaciones relacionadas con pacientes
  - name: Citas
    description: Operaciones relacionadas con citas médicas
  - name: Calendarizaciones
    description: Operaciones relacionadas con calendarizaciones médicas
  - name: Autenticación
    description: Operaciones relacionadas con la Seguridad

paths:
  /patients:
    post:
      tags:
        - Pacientes
      summary: Registrar un nuevo paciente
      operationId: createPatient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientRequest'
      responses:
        '201':
          description: Paciente registrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientResponse'
        '400':
          description: Datos de entrada inválidos
        '409':
          description: Paciente ya existe
        '500':
          description: Error interno del servidor

  /patients/{id}:
    get:
      tags:
        - Pacientes
      summary: Consultar paciente por su id (cédula)
      operationId: getPatientById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Cédula del paciente
      responses:
        '200':
          description: Paciente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientResponse'
        '204':
          description: Paciente no encontrado
        '403':
          description: Acceso denegado
        '500':
          description: Error interno del servidor

  /appointments:
    get:
      tags:
        - Citas
      summary: Listar todas las citas médicas
      operationId: getAllAppointments
      responses:
        '200':
          description: Lista de citas médicas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppointmentResponse'
        '500':
          description: Error interno del servidor
    post:
      tags:
        - Citas
      summary: Crear una nueva cita médica
      operationId: createAppointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentRequest'
      responses:
        '201':
          description: Cita médica creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse'
        '400':
          description: Datos de entrada inválidos
        '404':
          description: Paciente no encontrado
        '409':
          description: El horario ya está ocupado
        '500':
          description: Error interno del servidor

  /appointments/{id}:
    get:
      tags:
        - Citas
      summary: Consultar cita médica por ID
      operationId: getAppointmentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID único de la cita médica
      responses:
        '200':
          description: Cita médica encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse'
        '204':
          description: Cita médica no encontrada
        '500':
          description: Error interno del servidor
    delete:
      tags:
        - Citas
      summary: Cancelar cita médica
      operationId: cancelAppointment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID único de la cita médica
      responses:
        '204':
          description: Cita médica cancelada exitosamente
        '404':
          description: Cita médica no encontrada
        '500':
          description: Error interno del servidor

  /calendarizations:
    get:
      tags:
        - Calendarizaciones
      summary: Listar todas las calendarizaciones
      operationId: getAllCalendarizations
      responses:
        '200':
          description: Lista de calendarizaciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CalendarizationResponse'
        '500':
          description: Error interno del servidor
    post:
      tags:
        - Calendarizaciones
      summary: Crear una nueva calendarización
      operationId: createCalendarization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalendarizationRequest'
      responses:
        '201':
          description: Calendarización creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarizationResponse'
        '400':
          description: Datos de entrada inválidos
        '500':
          description: Error interno del servidor

  /calendarizations/{id}:
    get:
      tags:
        - Calendarizaciones
      summary: Consultar calendarización por ID
      operationId: getCalendarizationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID de la calendarización
      responses:
        '200':
          description: Calendarización encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarizationResponse'
        '204':
          description: Calendarización no encontrada
        '500':
          description: Error interno del servidor
    put:
      tags:
        - Calendarizaciones
      summary: Actualizar calendarización
      operationId: updateCalendarization
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID de la calendarización
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalendarizationRequest'
      responses:
        '200':
          description: Calendarización actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarizationResponse'
        '400':
          description: Datos de entrada inválidos
        '204':
          description: Calendarización no encontrada
        '500':
          description: Error interno del servidor
    delete:
      tags:
        - Calendarizaciones
      summary: Eliminar calendarización
      operationId: deleteCalendarization
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID de la calendarización
      responses:
        '204':
          description: Calendarización eliminada exitosamente
        '404':
          description: Calendarización no encontrada
        '500':
          description: Error interno del servidor

  /auth/login:
    post:
      tags:
        - Autenticación
      summary: Iniciar sesión.
      operationId: authLogin
      description: Autenticacion en sistema
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Login exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '403':
          description: No autorizado para acceder a este recurso
        '500':
          description: Error al autenticarse

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    PatientResponse:
      type: object
      required:
        - id
        - name
        - email
        - phone
      properties:
        id:
          type: string
          description: Cédula del paciente
          example: "1234567890"
        name:
          type: string
          description: Nombre completo del paciente
          example: "María Elena González"
        email:
          type: string
          format: email
          description: Correo electrónico del paciente
          example: "maria.gonzalez@gmail.com"
        phone:
          type: string
          description: Teléfono del paciente
          example: "0987654321"

    PatientRequest:
      type: object
      required:
        - id
        - name
        - email
        - phone
      properties:
        id:
          type: string
          minLength: 10
          maxLength: 10
          pattern: '^[0-9]{10}$'
          description: Cédula del paciente
          example: "1234567890"
        name:
          type: string
          minLength: 2
          maxLength: 100
          description: Nombre completo del paciente
          example: "María Elena González"
        email:
          type: string
          format: email
          description: Correo electrónico del paciente
          example: "maria.gonzalez@gmail.com"
        phone:
          type: string
          minLength: 10
          maxLength: 15
          pattern: '^[0-9]+$'
          description: Teléfono del paciente
          example: "0987654321"

    AppointmentRequest:
      type: object
      required:
        - patientId
        - calendarizationId
      properties:
        patientId:
          type: string
          minLength: 10
          maxLength: 10
          pattern: '^[0-9]{10}$'
          description: Cédula del paciente
          example: "1234567890"
        calendarizationId:
          type: integer
          format: int64
          description: ID de la calendarización (horario disponible)
          example: 1

    AppointmentResponse:
      type: object
      required:
        - id
        - patient
        - calendarization
        - creationDate
        - status
      properties:
        id:
          type: string
          description: ID único de la cita médica
          example: "apt-001"
        patient:
          $ref: '#/components/schemas/PatientResponse'
        calendarization:
          $ref: '#/components/schemas/CalendarizationResponse'
        creationDate:
          type: string
          format: date-time
          description: Fecha y hora de creación de la cita
          example: "2024-01-15T14:30:00"
        modificationDate:
          type: string
          format: date-time
          description: Fecha y hora de última modificación
          example: "2024-01-15T15:00:00"
        status:
          type: string
          description: Estado de la cita
          example: "ACTIVE"
          enum:
            - ACTIVE
            - CANCELLED

    CalendarizationResponse:
      type: object
      required:
        - id
        - doctor
        - branch
        - schedule
      properties:
        id:
          type: integer
          format: int64
          description: ID de la calendarización
          example: 1
        doctor:
          $ref: '#/components/schemas/DoctorResponse'
        branch:
          $ref: '#/components/schemas/BranchResponse'
        schedule:
          type: string
          format: date-time
          description: Fecha y hora del horario
          example: "2024-01-15T14:30:00"
        active:
          type: boolean
          description: Estado activo de la calendarización
          example: true

    DoctorResponse:
      type: object
      required:
        - id
        - name
        - cedula
        - specialty
      properties:
        id:
          type: integer
          format: int64
          description: ID del médico
          example: 1
        name:
          type: string
          description: Nombre del médico
          example: "Dr. Juan Pérez"
        cedula:
          type: string
          description: Cédula del médico
          example: "1001234567"
        specialty:
          $ref: '#/components/schemas/SpecialtyResponse'
        active:
          type: boolean
          description: Estado activo del médico
          example: true

    BranchResponse:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: ID de la sucursal
          example: 1
        name:
          type: string
          description: Nombre de la sucursal
          example: "Sucursal Norte"
        address:
          type: string
          description: Dirección de la sucursal
          example: "Av. Principal 123"
        active:
          type: boolean
          description: Estado activo de la sucursal
          example: true

    SpecialtyResponse:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: ID de la especialidad
          example: 1
        name:
          type: string
          description: Nombre de la especialidad
          example: "Traumatología"
        active:
          type: boolean
          description: Estado activo de la especialidad
          example: true

    CalendarizationRequest:
      type: object
      required:
        - doctorId
        - branchId
        - schedule
      properties:
        doctorId:
          type: integer
          format: int64
          description: ID del médico
          example: 1
        branchId:
          type: integer
          format: int64
          description: ID de la sucursal
          example: 1
        schedule:
          type: string
          format: date-time
          description: Fecha y hora del horario
          example: "2024-01-15T14:30:00"

    AuthRequest:
      type: object
      required:
        - userName
        - password
      properties:
        userName:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        token:
          type: string

security:
  - bearerAuth: [ ]