quarkus:
  http:
    port: 8282
    auth:
      permission:
        public-endpoints:
          paths:
            - /auth/*
            - /q/swagger-ui/*
            - /q/openapi
            - /q/health
            - /q/metrics
          policy: permit
        protected-endpoints:
          paths:
            - /*
          policy: authenticated
  datasource:
    db-kind: postgresql
    username: ${APP_CONFIG_DATABASE_USERNAME}
    password: ${APP_CONFIG_DATABASE_PASSWORD}
    jdbc:
      url: jdbc:postgresql://${APP_CONFIG_DATABASE_SERVER}:${APP_CONFIG_DATABASE_PORT}/${APP_CONFIG_DATABASE_NAME}
  hibernate-orm:
    schema-management:
      strategy: none

  log:
    category:
      "com.healthcare.apps.patient":
        level: TRACE
      "org.hibernate.SQL":
        level: TRACE
      "org.hibernate.type.descriptor.sql.BasicBinder":
        level: TRACE
      "io.smallrye.jwt":
        level: TRACE
      "io.quarkus.security":
        level: TRACE

mp:
  jwt:
    verify:
      publickey:
        location: classpath:keys/publicKey.pem
      issuer: csip
      #clock-skew: PT30S
    require:
      iat: true
smallrye:
  jwt:
    sign:
      key:
        location: classpath:keys/privateKey.pem