quarkus:
  http:
    port: 8282
  datasource:
    db-kind: postgresql
    username: postgres
    password: 123456789
    jdbc:
      url: jdbc:postgresql://localhost:5432/db_patient_management
  hibernate-orm:
    schema-management:
      strategy: update