quarkus:
  http:
    port: 8282
    auth:
      permission:
        public-endpoints:
          paths:
            - /auth/*
            - /q/swagger-ui/*
            - /q/openapi
            - /q/health
            - /q/metrics
          policy: permit
        protected-endpoints:
          paths:
            - /*
          policy: authenticated
  datasource:
    db-kind: postgresql
    username: postgres
    password: 123456789
    jdbc:
      url: jdbc:postgresql://localhost:5432/db_patient_management
  hibernate-orm:
    schema-management:
      strategy: none

mp:
  jwt:
    verify:
      publickey:
        location: classpath:keys/publicKey.pem
      issuer: csip
smallrye:
  jwt:
    sign:
      key:
        location: classpath:keys/privateKey.pem